name: CMake Build Matrix

on: [push]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Windows Latest MinGW", artifact: "Windows.tar.xz",
            os: windows-latest,
            build_type: "Release", cc: "clang", cxx: "clang++"
          }
        - {
            name: "Ubuntu", artifact: "Linux.tar.xz",
            os: ubuntu-latest,
            build_type: "Release", cc: "clang", cxx: "clang++"
          }
        - {
            name: "macOS", artifact: "macOS.tar.xz",
            os: macos-latest,
            build_type: "Release", cc: "clang", cxx: "clang++"
          }
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: cmake .
    - name: make
      run: cmake --build .
