name: CMake Build Matrix

on: [push]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Windows",
            artifact: "Windows.tar.xz",
            os: windows-latest,
            build_type: "Release",
            cxx: "clang++"
          }
        - {
            name: "Ubuntu",
            artifact: "Linux.tar.xz",
            os: ubuntu-latest,
            build_type: "Release",
            cxx: "clang++-9",
            cxxflags: "-stdlib=libc++"
          }
        - {
            name: "macOS",
            artifact: "macOS.tar.xz",
            os: macos-latest,
            build_type: "Release"
          }
    steps:
    - uses: actions/checkout@v2
    - name: configure
      env:
        CXXFLAGS: ${{ matrix.cxxflags }}
        CXX: ${{ matrix.cxx }}
      run: mkdir build && cd build && cmake ..
    - name: make
      run: cmake --build .
    - name: test
      env:
        CTEST_PARALLEL_LEVEL: 8
      run: ctest
    - name: deploy
      run: cmake --build . --target package
